# version: "3.4"

networks:
  lastdance:
    name: lastdance
    driver: bridge
  
services:
  user:
    container_name: userservice
    build: ./authService 
    entrypoint: ./start.sh
    command: uvicorn auth.asgi:application --host 0.0.0.0 --port 8000 --reload
    environment:
      USER_DB_USER: ${USER_DB_USER}
      USER_DB_PASS: ${USER_DB_PASS}
      USER_DB_NAME: ${USER_DB_NAME}
      USER_DB_HOST: ${USER_DB_HOST}
      USER_DB_PORT: ${USER_DB_PORT}
    volumes:
      - authService:/authServices
    networks:
      - lastdance
    depends_on:
      - users_db

  front_end:
    container_name: front_end
    build: ./nginx
    restart: always
    volumes:
      - /etc/letsencrypt/live/lastdance.com.tr/fullchain.pem:/etc/letsencrypt/live/lastdance.com.tr/fullchain.pem:ro
      - /etc/letsencrypt/live/lastdance.com.tr/privkey.pem:/etc/letsencrypt/live/lastdance.com.tr/privkey.pem:ro
      - ./nginx/conf/default.conf:/etc/nginx/nginx.conf
      - ./nginx/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    networks:
      - lastdance
    depends_on:
      - user

  users_db:
    container_name: users_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: Zodiyac123++
      POSTGRES_DB: users
    volumes:
      - user_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - lastdance
  
volumes:
  user_db:
  authService:
