# Generated by Django 5.0.6 on 2024-09-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profil_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='otp_secret_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
