# Generated by Django 5.0.6 on 2024-09-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profil_otp_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='otp_secret_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
