# Generated by Django 5.0.6 on 2024-09-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profil_otp_secret_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='is_online',
        ),
        migrations.AddField(
            model_name='profil',
            name='alias_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='lose',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='status',
            field=models.CharField(choices=[('ON', 'ONLINE'), ('OF', 'OFFLINE'), ('IG', 'INGAME')], default='OF', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='win',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
