# Generated by Django 5.0.6 on 2024-09-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_profil_is_online_profil_alias_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='lose',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='win',
        ),
        migrations.AddField(
            model_name='profil',
            name='championships',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profil',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profil',
            name='wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profil',
            name='alias_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='status',
            field=models.CharField(choices=[('ON', 'ONLINE'), ('OF', 'OFFLINE'), ('IG', 'INGAME')], default='OF', max_length=2),
        ),
    ]
