# Generated by Django 5.0.6 on 2024-09-15 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_profil_lose_remove_profil_win_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('round', models.IntegerField(default=1)),
                ('state', models.CharField(choices=[('PLY', 'PLAYED'), ('UPL', 'UNPLAYED')], default='UPL', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('round', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('PN', 'PENDING'), ('PG', 'IN_PROGRESS'), ('FN', 'FINISHED')], default='PN', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0)),
                ('won', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profil')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTournament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creator', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profil')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.tournament'),
        ),
    ]
