FROM python:3.12.4-alpine3.20

RUN apt-get update -y

COPY requirements.txt	.
#Bu main kanka settings olan
COPY game				.
#COPY users				. Buraya game in backi gelcek app olarak
COPY manage.py			.

RUN pip install --no-cache-dir -r requirements.txt

