# Generated by Django 5.0.6 on 2024-07-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_catagory_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='catagory_id',
        ),
        migrations.AddField(
            model_name='blog',
            name='catagories',
            field=models.ManyToManyField(to='blog.catagory'),
        ),
    ]
